services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8008
    volumes:
      - .:/app
      - ./logs:/app/logs
    env_file:
      - .env
    ports:
      - "8008:8008"
    restart: always
