# Generated by Django 5.2 on 2026-04-07 08:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MonitorTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='사이트 이름')),
                ('url', models.URLField(verbose_name='모니터링 대상 URL')),
                ('check_interval', models.IntegerField(default=300, verbose_name='체크 주기 (초)')),
                ('signatures', models.JSONField(default=dict, verbose_name='정상 판단 시그니처')),
                ('recipients', models.JSONField(default=list, verbose_name='알림 수신 대상 (Webhook URL)')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성 여부')),
                ('last_status', models.CharField(blank=True, choices=[('UP', 'UP'), ('DOWN', 'DOWN')], max_length=10, null=True, verbose_name='마지막 상태')),
                ('last_checked_at', models.DateTimeField(blank=True, null=True, verbose_name='마지막 체크 시간')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '모니터링 대상',
                'verbose_name_plural': '모니터링 대상',
            },
        ),
        migrations.CreateModel(
            name='MonitoringLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=10, verbose_name='상태')),
                ('response_time', models.FloatField(verbose_name='응답 시간 (초)')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='에러 메시지')),
                ('checked_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='체크 시간')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='web_monitor.monitortarget', verbose_name='대상 사이트')),
            ],
            options={
                'verbose_name': '모니터링 로그',
                'verbose_name_plural': '모니터링 로그',
                'ordering': ['-checked_at'],
            },
        ),
    ]
