# Generated by Django 5.1.6 on 2026-04-07 08:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_monitor', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='monitortarget',
            name='signature_dom',
            field=models.TextField(blank=True, null=True, verbose_name='시그니처: DOM Selector (쉼표로 구분)'),
        ),
        migrations.AddField(
            model_name='monitortarget',
            name='signature_text',
            field=models.TextField(blank=True, null=True, verbose_name='시그니처: Text (쉼표로 구분)'),
        ),
        migrations.AddField(
            model_name='monitortarget',
            name='signature_title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='시그니처: Title'),
        ),
        migrations.RemoveField(
            model_name='monitortarget',
            name='recipients',
        ),
        migrations.AlterField(
            model_name='monitortarget',
            name='signatures',
            field=models.JSONField(blank=True, default=dict, verbose_name='정상 판단 시그니처 (레거시)'),
        ),
        migrations.AddField(
            model_name='monitortarget',
            name='recipients',
            field=models.ManyToManyField(related_name='monitoring_targets', to=settings.AUTH_USER_MODEL, verbose_name='알림 수신 대상자'),
        ),
    ]
