# Generated by Django 5.2 on 2026-04-09 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_monitor', '0002_monitortarget_signature_dom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitortarget',
            name='log_retention_days',
            field=models.IntegerField(default=7, verbose_name='로그 보관 주기 (일)'),
        ),
    ]
