# Generated by Django 5.1.6 on 2026-04-10 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_monitor', '0003_monitortarget_log_retention_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoringlog',
            name='pinned_file',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='박제된 파일명'),
        ),
    ]
