# Generated by Django 5.1.6 on 2026-04-13 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_monitor', '0004_monitoringlog_pinned_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='TargetRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='이름')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='이메일')),
            ],
        ),
        migrations.AlterField(
            model_name='monitortarget',
            name='recipients',
            field=models.ManyToManyField(related_name='monitoring_targets', to='web_monitor.targetrecipient', verbose_name='알림 수신 대상자'),
        ),
    ]
