# Generated by Django 5.2 on 2026-04-14 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_monitor', '0005_targetrecipient_alter_monitortarget_recipients'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitortarget',
            name='last_status_changed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='상태 변경 시간'),
        ),
    ]
