# Generated by Django 5.2 on 2026-04-17 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_monitor', '0006_monitortarget_last_status_changed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitortarget',
            name='timeout',
            field=models.IntegerField(default=20, verbose_name='타임아웃 (초)'),
        ),
    ]
