# Generated by Django 5.0.6 on 2026-07-28 05:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_monitor', '0007_monitortarget_timeout'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitortarget',
            name='last_size_bytes',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='마지막 측정 사이즈 (Bytes)'),
        ),
        migrations.AddField(
            model_name='monitortarget',
            name='last_size_checked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='마지막 사이즈 측정 시간'),
        ),
        migrations.CreateModel(
            name='WebsiteSizeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_size_bytes', models.BigIntegerField(default=0, verbose_name='총 사이즈 (Bytes)')),
                ('html_size', models.BigIntegerField(default=0, verbose_name='HTML 사이즈 (Bytes)')),
                ('resource_size', models.BigIntegerField(default=0, verbose_name='리소스 사이즈 (Bytes)')),
                ('resource_count', models.IntegerField(default=0, verbose_name='리소스 개수')),
                ('status', models.CharField(choices=[('SUCCESS', '성공'), ('FAILED', '실패')], default='SUCCESS', max_length=10, verbose_name='상태')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='에러 메시지')),
                ('checked_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='측정 시간')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='size_logs', to='web_monitor.monitortarget', verbose_name='대상 사이트')),
            ],
            options={
                'verbose_name': '웹사이트 사이즈 로그',
                'verbose_name_plural': '웹사이트 사이즈 로그',
                'ordering': ['-checked_at'],
            },
        ),
    ]
